/********************************************************************
* T49ANADict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error T49ANADict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableT49ANADict();
extern void G__cpp_setup_inheritanceT49ANADict();
extern void G__cpp_setup_typetableT49ANADict();
extern void G__cpp_setup_memvarT49ANADict();
extern void G__cpp_setup_globalT49ANADict();
extern void G__cpp_setup_memfuncT49ANADict();
extern void G__cpp_setup_funcT49ANADict();
extern void G__set_cpp_environmentT49ANADict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "PhysConst.h"
#include "T49Cut.h"
#include "T49CutEvent.h"
#include "T49CutTrack.h"
#include "T49Cut2Track.h"
#include "T49CutV0.h"
#include "T49CutPid.h"
#include "T49Dedx.h"
#include "T49DedxFunction.h"
#include "T49DedxInfo.h"
#include "T49InMuDST.h"
#include "T49Mixing.h"
#include "T49Mixer.h"
#include "T49MultiMixer.h"
#include "T49Prob.h"
#include "T49Proj1.h"
#include "T49Proj2.h"
#include "T49Tool.h"
#include "T49Histogram.h"
#include "T49Histogram1D.h"
#include "T49Histogram2D.h"
#include "T49Histogram3D.h"
#include "T49Container.h"
#include "T49Index.h"
#include "T49OnePeak.h"
#include "T49SumGaus.h"
#include "T49Trkstep.h"
#include "T49Padtrans.h"
#include "T49XiFinder.h"
#include "T49HbtMomentumResolutionCalculation.h"
#include "T49HbtMomentumResolutionCorrection.h"
#include "T49HbtCoulomb.h"
#include "T49HbtFitBase.h"
#include "T49HbtFitDivers.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__T49ANADictLN_TClass;
extern G__linked_taginfo G__T49ANADictLN_TBuffer;
extern G__linked_taginfo G__T49ANADictLN_TMemberInspector;
extern G__linked_taginfo G__T49ANADictLN_TObject;
extern G__linked_taginfo G__T49ANADictLN_TNamed;
extern G__linked_taginfo G__T49ANADictLN_TCollection;
extern G__linked_taginfo G__T49ANADictLN_TString;
extern G__linked_taginfo G__T49ANADictLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR;
extern G__linked_taginfo G__T49ANADictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__T49ANADictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__T49ANADictLN_TObjArray;
extern G__linked_taginfo G__T49ANADictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__T49ANADictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__T49ANADictLN_T49Cut;
extern G__linked_taginfo G__T49ANADictLN_TPaveText;
extern G__linked_taginfo G__T49ANADictLN_T49EventRoot;
extern G__linked_taginfo G__T49ANADictLN_T49CutEvent;
extern G__linked_taginfo G__T49ANADictLN_TArrayI;
extern G__linked_taginfo G__T49ANADictLN_TF1;
extern G__linked_taginfo G__T49ANADictLN_T49ParticleRoot;
extern G__linked_taginfo G__T49ANADictLN_T49Prob;
extern G__linked_taginfo G__T49ANADictLN_T49CutTrack;
extern G__linked_taginfo G__T49ANADictLN_T49Particle;
extern G__linked_taginfo G__T49ANADictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__T49ANADictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__T49ANADictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__T49ANADictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__T49ANADictLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__T49ANADictLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__T49ANADictLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__T49ANADictLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__T49ANADictLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__T49ANADictLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__T49ANADictLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__T49ANADictLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__T49ANADictLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__T49ANADictLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__T49ANADictLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__T49ANADictLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__T49ANADictLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__T49ANADictLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__T49ANADictLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__T49ANADictLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__T49ANADictLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__T49ANADictLN_TVector3;
extern G__linked_taginfo G__T49ANADictLN_TLorentzVector;
extern G__linked_taginfo G__T49ANADictLN_T49Tool;
extern G__linked_taginfo G__T49ANADictLN_T49Cut2Track;
extern G__linked_taginfo G__T49ANADictLN_T49VertexRoot;
extern G__linked_taginfo G__T49ANADictLN_T49CutV0;
extern G__linked_taginfo G__T49ANADictLN_TSeqCollection;
extern G__linked_taginfo G__T49ANADictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__T49ANADictLN_TFile;
extern G__linked_taginfo G__T49ANADictLN_TArrayC;
extern G__linked_taginfo G__T49ANADictLN_TAttFill;
extern G__linked_taginfo G__T49ANADictLN_TAttLine;
extern G__linked_taginfo G__T49ANADictLN_TAttMarker;
extern G__linked_taginfo G__T49ANADictLN_TArrayD;
extern G__linked_taginfo G__T49ANADictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR;
extern G__linked_taginfo G__T49ANADictLN_TH1;
extern G__linked_taginfo G__T49ANADictLN_TFormula;
extern G__linked_taginfo G__T49ANADictLN_TAxis;
extern G__linked_taginfo G__T49ANADictLN_TH1D;
extern G__linked_taginfo G__T49ANADictLN_TH1F;
extern G__linked_taginfo G__T49ANADictLN_T49Index;
extern G__linked_taginfo G__T49ANADictLN_T49DedxInfo;
extern G__linked_taginfo G__T49ANADictLN_T49Container;
extern G__linked_taginfo G__T49ANADictLN_T49CutPid;
extern G__linked_taginfo G__T49ANADictLN_TF2;
extern G__linked_taginfo G__T49ANADictLN_T49Dedx;
extern G__linked_taginfo G__T49ANADictLN_T49DedxFunction;
extern G__linked_taginfo G__T49ANADictLN_TStyle;
extern G__linked_taginfo G__T49ANADictLN_TRandom;
extern G__linked_taginfo G__T49ANADictLN_vectorlETStringcOallocatorlETStringgRsPgR;
extern G__linked_taginfo G__T49ANADictLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__T49ANADictLN_TProfile;
extern G__linked_taginfo G__T49ANADictLN_TH2C;
extern G__linked_taginfo G__T49ANADictLN_TH2D;
extern G__linked_taginfo G__T49ANADictLN_TH3D;
extern G__linked_taginfo G__T49ANADictLN_T49InMuDST;
extern G__linked_taginfo G__T49ANADictLN_T49Mixing;
extern G__linked_taginfo G__T49ANADictLN_TDialogCanvas;
extern G__linked_taginfo G__T49ANADictLN_T49Mixer;
extern G__linked_taginfo G__T49ANADictLN_T49Proj2BASE;
extern G__linked_taginfo G__T49ANADictLN_T49MultiMixer;
extern G__linked_taginfo G__T49ANADictLN_TGraph;
extern G__linked_taginfo G__T49ANADictLN_T49Proj1BASE;
extern G__linked_taginfo G__T49ANADictLN_T49Proj1Dedx;
extern G__linked_taginfo G__T49ANADictLN_T49Proj1Prob;
extern G__linked_taginfo G__T49ANADictLN_T49Proj2BP;
extern G__linked_taginfo G__T49ANADictLN_T49Proj2YKP;
extern G__linked_taginfo G__T49ANADictLN_T49Proj2QtQl;
extern G__linked_taginfo G__T49ANADictLN_T49Proj2Armenteros;
extern G__linked_taginfo G__T49ANADictLN_T49Proj2QINV;
extern G__linked_taginfo G__T49ANADictLN_T49Proj2QINV2;
extern G__linked_taginfo G__T49ANADictLN_T49Proj2INVmass;
extern G__linked_taginfo G__T49ANADictLN_T49Proj2K;
extern G__linked_taginfo G__T49ANADictLN_T49Histogram;
extern G__linked_taginfo G__T49ANADictLN_T49Histogram1D;
extern G__linked_taginfo G__T49ANADictLN_T49Histogram2D;
extern G__linked_taginfo G__T49ANADictLN_T49Histogram3D;
extern G__linked_taginfo G__T49ANADictLN_T49OnePeak;
extern G__linked_taginfo G__T49ANADictLN_T49SumGaus;
extern G__linked_taginfo G__T49ANADictLN_T49Trkstep;
extern G__linked_taginfo G__T49ANADictLN_T49Padtrans;
extern G__linked_taginfo G__T49ANADictLN_T49XiFinder;
extern G__linked_taginfo G__T49ANADictLN_T49ParticleMCRoot;
extern G__linked_taginfo G__T49ANADictLN_T49HbtMomentumResolutionCalculator;
extern G__linked_taginfo G__T49ANADictLN_T49HbtMomentumResolutionProvider;
extern G__linked_taginfo G__T49ANADictLN_T49HbtCoulomb;
extern G__linked_taginfo G__T49ANADictLN_T49HbtMomentumResolutionCorrection;
extern G__linked_taginfo G__T49ANADictLN_TMinuit;
extern G__linked_taginfo G__T49ANADictLN_T49HbtFitBase;
extern G__linked_taginfo G__T49ANADictLN_T49FitProjector;
extern G__linked_taginfo G__T49ANADictLN_T49HbtFit_BP_LS_CHI2;
extern G__linked_taginfo G__T49ANADictLN_T49HbtFit_BP_LS_MML;
extern G__linked_taginfo G__T49ANADictLN_T49HbtFit_BP_ULS_CHI2;
extern G__linked_taginfo G__T49ANADictLN_T49HbtFit_YKP_LS_CHI2;

/* STUB derived class for protected member access */
