/********************************************************************
* T49CRDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error T49CRDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableT49CRDict();
extern void G__cpp_setup_inheritanceT49CRDict();
extern void G__cpp_setup_typetableT49CRDict();
extern void G__cpp_setup_memvarT49CRDict();
extern void G__cpp_setup_globalT49CRDict();
extern void G__cpp_setup_memfuncT49CRDict();
extern void G__cpp_setup_funcT49CRDict();
extern void G__set_cpp_environmentT49CRDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "PhysConst.h"
#include "T49CrDedx.h"
#include "T49CrInfo.h"
#include "T49CrIndex.h"
#include "T49CrParticle.h"
#include "T49CrContainer.h"
#include "T49CrMixer.h"
#include "T49CrSdynFit.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__T49CRDictLN_TClass;
extern G__linked_taginfo G__T49CRDictLN_TBuffer;
extern G__linked_taginfo G__T49CRDictLN_TMemberInspector;
extern G__linked_taginfo G__T49CRDictLN_TObject;
extern G__linked_taginfo G__T49CRDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__T49CRDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__T49CRDictLN_TObjArray;
extern G__linked_taginfo G__T49CRDictLN_TClonesArray;
extern G__linked_taginfo G__T49CRDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__T49CRDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__T49CRDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__T49CRDictLN_TFile;
extern G__linked_taginfo G__T49CRDictLN_TTree;
extern G__linked_taginfo G__T49CRDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR;
extern G__linked_taginfo G__T49CRDictLN_TF1;
extern G__linked_taginfo G__T49CRDictLN_TAxis;
extern G__linked_taginfo G__T49CRDictLN_T49ParticleRoot;
extern G__linked_taginfo G__T49CRDictLN_T49CrParticle;
extern G__linked_taginfo G__T49CRDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__T49CRDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__T49CRDictLN_TH1F;
extern G__linked_taginfo G__T49CRDictLN_T49CrIndex;
extern G__linked_taginfo G__T49CRDictLN_T49CrInfo;
extern G__linked_taginfo G__T49CRDictLN_T49CrContainer;
extern G__linked_taginfo G__T49CRDictLN_T49CrDedx;
extern G__linked_taginfo G__T49CRDictLN_TRandom;
extern G__linked_taginfo G__T49CRDictLN_T49CrMixer;
extern G__linked_taginfo G__T49CRDictLN_T49CrSdynFit;

/* STUB derived class for protected member access */
